### PR TITLE
Carrie Walsh

### PR DESCRIPTION
**Pull request by carriewalsh**
Here it is again!
I simplified it after practicing with initializing classes.

### CODE REVIEW

**Comment by ameseee** [comment]
Hi @carriewalsh! Thanks for all your hard work on Flashcards - you did great! I hope you had some fun with it too. Overall, this shows you are in a good place with the Week 1 learning goals. Because you've clearly got that down, I gave a few comments to continue pushing you - you can scroll up and read them or click on the `Files changed` tab and see them embedded in your code. One thing I didn't mention in there but as an overall - make sure to always remove all comments (unless absolutely necessary and that's rare), `require 'pry'` and extra white-space when you submit projects in the future. Please let me know if you have any questions regarding my notes.

**Comment by ameseee** [comment]
OOPS - I forgot to tell you:
🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯🎉💪💯
on those commit messages!!!

**Comment by carriewalsh** [comment]
Hey Thanks! What if I want to have comments for me so when I go back, I can remember things? Also, where is it best to put the whitespace? Between methods?

**Comment by carriewalsh** [comment]
Also, I don't understand where your comments are in the Files changed tab. Thanks!

**Pull request closed without merging**
